version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    build:
      context: ./mosquitto/
      dockerfile: ./Dockerfile
    volumes:
      - ./mosquitto/:/mosquitto/config/:ro
    ports:
      - 1883:1883

  rabbitmq:
    image: rabbitmq:3-management
    # hostname: my-rabbit
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: samples/postgres
    container_name: postgres
    ports:
      - "5432:5432"
    build:
      context: ./postgres/
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
