apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqldb
  namespace: dapr-cameradatacalculation
spec:
  type: bindings.postgres
  version: v1
  metadata:
    - name: url
      value: "user=postgres password=postgres host=localhost port=5432 dbname=employees pool_min_conns=1 pool_max_conns=10"
scopes:
  - employeestoreservice
  - employeeinfoservice
