apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecretstore
  namespace: dapr-cameradatacalculation
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: ../../../dapr/secrets.json
    - name: nestedSeparator
      value: "."
scopes:
  - employeeinfoservice
