version: "3.8"

services:
  dapr-postgres:
    image: samples/postgres
    container_name: postgres
    ports:
      - "5432:5432"
    build:
      context: ./db/
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - dapr-postgres
